version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=realState
      - DJANGO_DB_USER=nady
      - DJANGO_DB_PASSWORD=admin
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true # Keep the container open to inspect errors if necessary
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: realState
      POSTGRES_USER: nady
      POSTGRES_PASSWORD: admin
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
