# Generated by Django 5.1.5 on 2025-02-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="thumbnail",
        ),
    ]
